"""add pipeline_status to campaigns

Revision ID: 90ee79719402
Revises: 33bbbf4c2cd1
Create Date: 2026-03-28 22:57:14.978029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ee79719402'
down_revision: Union[str, None] = '33bbbf4c2cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('pipeline_status', sa.String(length=20), nullable=False, server_default='idle'))
    op.alter_column('campaigns', 'pipeline_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'pipeline_status')
    # ### end Alembic commands ###
